# YouTube Data API v3 key
# Get one from Google Cloud Console
youtube-data-api-key: abc123

#Отображать инфу в табе (нерекомендуется)
enable-tab-theater-list: false

#Разрешить дизлайки видосам в очереди
down_vote_enable: false

#Отображать полоски босс баров с временем и названием видео текущего
boss_bars_show_enable: true

storage:
  mysql:
    use: false
    host: localhost
    port: 3306
    database: cinemamod
    username: root
    password: password
  sqlite:
    use: true

# Theater types:
#   public - Все игроки могут запускать видео
#   perms - Только админы или игроки с правом cinemamod.perms могут запускать видео
#   static - Крутится одно видео 24/7, подходит для рекламы/пропаганды/стрима на твиче
#   x y z - координата верхего угла экрана, правый/левый зависит от facing (NORTH - левый)
#   facing - куда смотрит игрок = отразить (Если игрок смотрит в SOUTH -> то скрин NORTH)
#   first/second location - две точки которые формируют регион, в котором будет прогружаться видео

#theaters:
#  71b84249-27f5-4683-b362-97bafb38195a96051:
#    name: testname
#    hidden: false
#    type: perms
#    screen:
#      world: world
#      x: -7
#      y: 73
#      z: -36
#      facing: SOUTH
#      width: 8.0
#      height: 5.0
#      visible: true
#      muted: false
#    first_location:
#      world: world
#      x: -23
#      y: 82
#      z: -10
#    second_location:
#      x: 9
#      y: 60
#      z: -43

# (игнорировать) automatically makes 200x200x64 regions for testing when an existing region is not found
autogenCubicRegions: false