main: com.cinemamod.bukkit.CinemaModPlugin
name: CinemaMod
version: 1.0.6
api-version: 1.18
author: ds58, DenVer9
depend: [ ProtocolLib ]
commands:
  video:
    usage: /video help
    description: Команды для управления видосами
  cinema:
    usage: /cinema help
    description: Команды для управления кинотеатром
    permission: cinemamod.cinema
permissions:
  cinemamod.cinema:
    default: op
  cinemamod.perms:
    default: false
